version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: "mysql:8.0"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Azia/Tokyo"
    ports:
      - "3306:3306"

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - ./web:/usr/src/app
    environment:
      CHOKIDAR_USERPOLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - api
    tty: true
    stdin_open: true

volumes:
  db-volume: